- name: Remove VMPools
  include: vm_pools.yml

- name: Remove VMs
  include: vms.yml

- name: Remove Templates
  include: templates.yml

- name: Remove Disks
  include: disks.yml

- name: Find existing Storage Domains in Datacenter
  ovirt_storage_domains_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ data_center_name }}"

- name: Remove all Storage Domains except master
  include: storages_pre.yml

- name: Find existing clusters in Datacenter
  ovirt_clusters_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ data_center_name }}"

- name: Remove Datacenter
  include: datacenter.yml

- name: Remove master Storage Domain
  include: storages_last.yml

- name: Remove Clusters and Hosts
  include: cluster_and_hosts.yml
  with_items: "{{ ovirt_clusters }}"
  loop_control:
    loop_var: cluster_item
